# A (probably) complete list of additional blocks for 1.20.2
interactBlocks:
- BEACON
- CRAFTING_TABLE
- ENCHANTING_TABLE
- ENDER_CHEST
- COMPARATOR
- REPEATER
- DAYLIGHT_DETECTOR
- LEVER
- CARTOGRAPHY_TABLE
- GRINDSTONE
- LOOM
- STONECUTTER
- BELL
- SMITHING_TABLE
- NOTE_BLOCK
- CAKE